CompilationUnit:
  |PackageDeclaration| |ImportDeclarations| |TypeDeclaration|

Literal:
  IntegerLiteral
  BooleanLiteral
  CharacterLiteral
  StringLiteral
  NullLiteral

Type:
  PrimitiveType
  ReferenceType

PrimitiveType:
  IntegralType
  boolean

IntegralType:
  byte
  short
  int
  char

ReferenceType:
  ClassOrInterfaceType
  ArrayType

ClassOrInterfaceType:
  Name

ClassType:
  ClassOrInterfaceType

InterfaceType:
  ClassOrInterfaceType

ArrayType:
  PrimitiveType [ ]
  Name [ ]

Name:
  SimpleName
  QualifiedName

SimpleName:
  Identifier

QualifiedName:
  Name . Identifier

ImportDeclarations:
  ImportDeclaration
  ImportDeclarations ImportDeclaration

PackageDeclaration:
  package Name ;

ImportDeclaration:
  SingleTypeImportDeclaration
  TypeImportOnDemandDeclaration

SingleTypeImportDeclaration:
  import Name ;

TypeImportOnDemandDeclaration:
  import Name . * ;

TypeDeclaration:
  ClassDeclaration
  InterfaceDeclaration
  ;

Modifiers:
  MODIFIER
  Modifiers MODIFIER

ClassDeclaration:
  |Modifiers| class Identifier |Super| |Interfaces| ClassBody

Super:
  extends ClassType

Interfaces:
  implements InterfaceTypeList

InterfaceTypeList:
  InterfaceType
  InterfaceTypeList , InterfaceType

ClassBody:
  { |ClassBodyDeclarations| }

ClassBodyDeclarations:
  ClassBodyDeclaration
  ClassBodyDeclarations ClassBodyDeclaration

ClassBodyDeclaration:
  ClassMemberDeclaration
  StaticInitializer
  ConstructorDeclaration

ClassMemberDeclaration:
  FieldDeclaration
  MethodDeclaration

FieldDeclaration:
  |Modifiers| Type VariableDeclarator ;

VariableDeclarator:
  Identifier = Expression

MethodDeclaration:
  MethodHeader MethodBody

MethodHeader:
  |Modifiers| Type MethodDeclarator |Throws|
  |Modifiers| void MethodDeclarator |Throws|

MethodDeclarator:
  Identifier ( |FormalParameterList| )

FormalParameterList:
  FormalParameter
  FormalParameterList , FormalParameter

FormalParameter:
  Type Identifier

Throws:
  throws ClassTypeList

ClassTypeList:
  ClassType
  ClassTypeList , ClassType

MethodBody:
  Block
  ;
StaticInitializer:
  static Block

ConstructorDeclaration:
  |Modifiers| ConstructorDeclarator |Throws| ConstructorBody

ConstructorDeclarator:
  SimpleName ( |FormalParameterList| )

ConstructorBody:
  { |ExplicitConstructorInvocation| |BlockStatements| }

ExplicitConstructorInvocation:
  this ( |ArgumentList| ) ;

InterfaceDeclaration:
  |Modifiers| interface Identifier |ExtendsInterfaces| InterfaceBody

ExtendsInterfaces:
  extends InterfaceType
  ExtendsInterfaces , InterfaceType

InterfaceBody:
  { |InterfaceMemberDeclarations| }

InterfaceMemberDeclarations:
  InterfaceMemberDeclaration
  InterfaceMemberDeclarations InterfaceMemberDeclaration

InterfaceMemberDeclaration:
  AbstractMethodDeclaration

AbstractMethodDeclaration:
  MethodHeader ;

Block:
  { |BlockStatements| }

BlockStatements:
  BlockStatement
  BlockStatements BlockStatement

BlockStatement:
  LocalVariableDeclarationStatement
  Statement

LocalVariableDeclarationStatement:
  LocalVariableDeclaration ;

LocalVariableDeclaration:
  Type VariableDeclarator

Statement:
  StatementWithoutTrailingSubstatement
  IfThenStatement
  IfThenElseStatement
  WhileStatement
  ForStatement

StatementNoShortIf:
  StatementWithoutTrailingSubstatement
  IfThenElseStatementNoShortIf
  WhileStatementNoShortIf
  ForStatementNoShortIf

StatementWithoutTrailingSubstatement:
  Block
  EmptyStatement
  ExpressionStatement
  ReturnStatement

EmptyStatement:
  ;

ExpressionStatement:
  StatementExpression ;

StatementExpression:
  Assignment
  MethodInvocation
  ClassInstanceCreationExpression

IfThenStatement:
  if ( Expression ) Statement

IfThenElseStatement:
  if ( Expression ) StatementNoShortIf else Statement

IfThenElseStatementNoShortIf:
  if ( Expression ) StatementNoShortIf else StatementNoShortIf

WhileStatement:
  while ( Expression ) Statement

WhileStatementNoShortIf:
  while ( Expression ) StatementNoShortIf

ForStatement:
  for ( |LocalVariableDeclaration| ; |Expression| ; |StatementExpression| ) Statement

ForStatementNoShortIf:
  for ( |LocalVariableDeclaration| ; |Expression| ; |StatementExpression| ) StatementNoShortIf

ReturnStatement:
  return |Expression| ;

Primary:
  PrimaryNoNewArray
  ArrayCreationExpression

PrimaryNoNewArray:
  Literal
  this
  ( Expression )
  ClassInstanceCreationExpression
  FieldAccess
  MethodInvocation
  ArrayAccess

ClassInstanceCreationExpression:
  new ClassType ( |ArgumentList| )

ArgumentList:
  Expression
  ArgumentList , Expression

ArrayCreationExpression:
  new PrimitiveType DimExprs |Dims|
  new ClassOrInterfaceType DimExprs |Dims|

DimExprs:
  DimExpr
  DimExprs DimExpr

DimExpr:
  [ Expression ]

Dims:
  [ ]
  Dims [ ]

FieldAccess:
  Primary . Identifier

MethodInvocation:
  Name ( |ArgumentList| )
  Primary . Identifier ( |ArgumentList| )

ArrayAccess:
  Name [ Expression ]
  PrimaryNoNewArray [ Expression ]

PostfixExpression:
  Primary
  Name

UnaryExpression:
  - UnaryExpression
  UnaryExpressionNotPlusMinus

UnaryExpressionNotPlusMinus:
  PostfixExpression
  ~ UnaryExpression
  ! UnaryExpression
  CastExpression

CastExpression:
  ( PrimitiveType |Dims| ) UnaryExpression
  ( Expression ) UnaryExpressionNotPlusMinus
  ( Name Dims ) UnaryExpressionNotPlusMinus

MultiplicativeExpression:
  UnaryExpression
  MultiplicativeExpression OPERATOR_MULTIPLICATIVE UnaryExpression

AdditiveExpression:
  MultiplicativeExpression
  AdditiveExpression OPERATOR_ADDITIVE MultiplicativeExpression

RelationalExpression:
  AdditiveExpression
  RelationalExpression OPERATOR_COMPARE AdditiveExpression
  RelationalExpression instanceof ReferenceType

EqualityExpression:
  RelationalExpression
  EqualityExpression OPERATOR_EQUALITY RelationalExpression

ConditionalAndExpression:
  EqualityExpression
  ConditionalAndExpression OPERATOR_AND EqualityExpression

ConditionalOrExpression:
  ConditionalAndExpression
  ConditionalOrExpression OPERATOR_OR ConditionalAndExpression

ConditionalExpression:
  ConditionalOrExpression

AssignmentExpression:
  ConditionalExpression
  Assignment

Assignment:
  LeftHandSide OPERATOR_ASSIGN AssignmentExpression

LeftHandSide:
  Name
  FieldAccess
  ArrayAccess

Expression:
  AssignmentExpression
